services:
  postgres:
    image: postgres:13.5-alpine3.15
    env_file:
      - ./.env
    volumes:
      - ./docker/multiple-databases:/docker-entrypoint-initdb.d
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: "$ORY_KRATOS_DATABASE,$APP_DATABASE,$ORY_KETO_DATABASE"
    networks:
      - intranet

  kratos-migrate:
    image: "oryd/kratos:$ORY_KRATOS_VERSION"
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      LOG_LEVEL: debug
      DSN: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$ORY_KRATOS_DATABASE?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./JChat.Infrastructure/Files/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    image: "oryd/kratos:$ORY_KRATOS_VERSION"
    depends_on:
      - kratos-migrate
    env_file:
      - ./.env
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    environment:
      DEV: $DEBUG
      DSN: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$ORY_KRATOS_DATABASE?sslmode=disable&max_conns=20&max_idle_conns=4
      IDENTITY_DEFAULT_SCHEMA_URL: file:///etc/config/kratos/identity.schema.json
      SERVE_ADMIN_BASE_URL: http://127.0.0.1:4434/
      SERVE_PUBLIC_BASE_URL: $KRATOS_PUBLIC_URL
      SERVE_PUBLIC_CORS_ENABLED: true
      SERVE_PUBLIC_CORS_DEBUG: $DEBUG
      SERVE_PUBLIC_CORS_ALLOWED_ORIGINS: $PRESENTATION_URL,$API_URL
      SERVE_PUBLIC_CORS_ALLOWED_METHODS: GET,POST
      SERVE_PUBLIC_CORS_ALLOWED_HEADERS: $CORS_ALLOWED_HEADERS
      SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: $PRESENTATION_URL
      SELFSERVICE_WHITELISTED_RETURN_URLS: $PRESENTATION_URL
      SELFSERVICE_FLOWS_ERROR_UI_URL: $PRESENTATION_URL/error
      SELFSERVICE_FLOWS_SETTINGS_UI_URL: $PRESENTATION_URL/settings
      SELFSERVICE_FLOWS_RECOVERY_UI_URL: $PRESENTATION_URL/recovery
      SELFSERVICE_FLOWS_LOGIN_UI_URL: $PRESENTATION_URL/login
      SELFSERVICE_FLOWS_REGISTRATION_UI_URL: $PRESENTATION_URL/registration
      SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL: $PRESENTATION_URL/login
      COOKIES_DOMAIN: $MAIN_DOMAIN
      LOG_LEVEL: debug
      LOG_LEAK_SENSITIVE_VALUES: $DEBUG
      SECRETS_COOKIE: "-7593%ZSqRK=Su7XE*!5+LnjpkC8T$v+LpwyN%%2&zbp52bdxBnGRmReXULP7vyd"
      SECRETS_CIPHER: "_W%@JEcw*F^P4Cvk48rtPjjVbgJM*r_g"
    ports:
      - 4434:4434
    volumes:
      - type: bind
        source: ./JChat.Infrastructure/Files/kratos
        target: /etc/config/kratos
    networks:
      - intranet
    extra_hosts:
      - host:host-gateway

  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    links:
      - kratos:kratos
    volumes:
      - type: bind
        source: ./JChat.Infrastructure/Files/nginx
        target: /etc/nginx
    networks:
      - intranet
    extra_hosts:
      - host:host-gateway

  keto-migrate:
    image: "oryd/keto:$ORY_KETO_VERSION"
    links:
      - postgres:postgresd
    environment:
      LOG_LEVEL: debug
      DSN: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$ORY_KETO_DATABASE?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./JChat.Infrastructure/Files/keto
        target: /home/ory
    command: [ "migrate", "up", "-y" ]
    restart: on-failure
    networks:
      - intranet

  keto:
    image: "oryd/keto:$ORY_KETO_VERSION"
    depends_on:
      - keto-migrate
    links:
      - postgres:postgresd
    environment:
      DSN: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$ORY_KETO_DATABASE?sslmode=disable&max_conns=20&max_idle_conns=4
      LOG_LEVEL: debug
      LOG_LEAK_SENSITIVE_VALUES: true
    ports:
      - 4466:4466
      - 4467:4467
    volumes:
      - type: bind
        source: ./JChat.Infrastructure/Files/keto
        target: /home/ory
    networks:
      - intranet

volumes:
  pgdata:

networks:
  intranet:
