// <auto-generated />
using System;
using JChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JChat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220207131046_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JChat.Domain.Entities.Channel.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_channels_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_channels_deleted_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_channels_last_modified_by_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_channels_workspace_id");

                    b.HasIndex("Name", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_name_workspace_id");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.Channel.ChannelUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_channel_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_channel_users_user_id");

                    b.HasIndex("ChannelId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_users_channel_id_user_id");

                    b.ToTable("channel_users", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("BodyTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("body_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<Guid>("MessageBodyTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_body_type_id");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uuid")
                        .HasColumnName("priority_id");

                    b.Property<Guid?>("ReplyingToId")
                        .HasColumnType("uuid")
                        .HasColumnName("replying_to_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_messages_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_messages_deleted_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_messages_last_modified_by_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessageBodyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_message_body_types");

                    b.ToTable("message_body_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bad45cd-595e-48c9-aff8-b927e2b30851"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.type.audio"
                        },
                        new
                        {
                            Id = new Guid("60f47ec7-5025-4e55-892b-7b1f2c444ee0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.type.gif"
                        },
                        new
                        {
                            Id = new Guid("f082a1f1-74de-4349-9ed6-24fe42188aea"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.type.image"
                        },
                        new
                        {
                            Id = new Guid("87159cfd-1db5-42ec-9250-084b3fc41964"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.type.text"
                        },
                        new
                        {
                            Id = new Guid("35cbb295-74cc-4157-9253-91c76492a1f2"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.type.video"
                        },
                        new
                        {
                            Id = new Guid("d10bef76-e162-41dd-a625-bb04d24b0064"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.type.channel_event"
                        });
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessageHighlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_message_highlights");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_message_highlights_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_message_highlights_deleted_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_message_highlights_last_modified_by_id");

                    b.ToTable("message_highlights", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessagePriority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_message_priorities");

                    b.ToTable("message_priorities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("195348d7-5de2-465c-ab01-89e76b7823cf"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.priority.normal"
                        },
                        new
                        {
                            Id = new Guid("8eafa8fe-dfae-4143-8abe-53e57d2d427c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.priority.snooze"
                        },
                        new
                        {
                            Id = new Guid("55cd213f-5a4f-40a1-8b3e-1b0aef8c0847"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.priority.requires_confirmation"
                        },
                        new
                        {
                            Id = new Guid("2efd5971-81aa-4f7e-94ff-c49b2827f945"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "message.priority.requires_confirmation_snooze"
                        });
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessageProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("BodyTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("body_type_id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("ConfirmedVisualizationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_visualization_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ForwardedById")
                        .HasColumnType("uuid")
                        .HasColumnName("forwarded_by_id");

                    b.Property<bool>("IsInbound")
                        .HasColumnType("boolean")
                        .HasColumnName("is_inbound");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uuid")
                        .HasColumnName("priority_id");

                    b.Property<string>("Reactions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reactions");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid?>("ReplyingToId")
                        .HasColumnType("uuid")
                        .HasColumnName("replying_to_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.HasKey("Id")
                        .HasName("pk_message_projections");

                    b.HasIndex("BodyTypeId")
                        .HasDatabaseName("ix_message_projections_body_type_id");

                    b.HasIndex("PriorityId")
                        .HasDatabaseName("ix_message_projections_priority_id");

                    b.HasIndex("ChannelId", "RecipientId")
                        .HasDatabaseName("ix_message_projections_channel_id_recipient_id");

                    b.ToTable("message_projections", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessageReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("ReactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reaction_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_message_reactions");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_message_reactions_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_message_reactions_deleted_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_message_reactions_last_modified_by_id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_reactions_message_id");

                    b.ToTable("message_reactions", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessageRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("ConfirmedVisualizationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_visualization_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<Guid?>("ForwardedById")
                        .HasColumnType("uuid")
                        .HasColumnName("forwarded_by_id");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_message_recipients");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_message_recipients_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_message_recipients_deleted_by_id");

                    b.HasIndex("ForwardedById")
                        .HasDatabaseName("ix_message_recipients_forwarded_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_message_recipients_last_modified_by_id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_recipients_message_id");

                    b.ToTable("message_recipients", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reactions");

                    b.ToTable("reactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e342b7ac-cd01-40fd-a60f-63a03706ccd8"),
                            Color = "1A85BA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "thumbs-up",
                            Name = "reaction.like"
                        },
                        new
                        {
                            Id = new Guid("009770db-2901-4462-aded-0b55a3d42939"),
                            Color = "6EAD51",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "celebrate",
                            Name = "reaction.celebrate"
                        },
                        new
                        {
                            Id = new Guid("f83577a7-7dad-4cc0-a2b9-d3e184f6a863"),
                            Color = "DA7150",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "love",
                            Name = "reaction.love"
                        },
                        new
                        {
                            Id = new Guid("c36aeceb-d569-4a34-a93f-9063c702e91d"),
                            Color = "F0B85F",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "insightful",
                            Name = "reaction.insightful"
                        },
                        new
                        {
                            Id = new Guid("b4ac3b4a-ddba-48e4-b04b-d71aacbe5a64"),
                            Color = "DCB9DA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "curious",
                            Name = "reaction.curious"
                        },
                        new
                        {
                            Id = new Guid("58b572f9-16dd-457d-9dc3-2fc531ba2436"),
                            Color = "CE5044",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "rocket",
                            Name = "reaction.rocket"
                        },
                        new
                        {
                            Id = new Guid("a8d26691-b652-46ee-a9c0-5faeb52c340a"),
                            Color = "FFFFFF",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "eyes",
                            Name = "reaction.eyes"
                        });
                });

            modelBuilder.Entity("JChat.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("meta");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_notifications_created_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_notifications_workspace_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.User.UserWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<bool>("Admin")
                        .HasColumnType("boolean")
                        .HasColumnName("admin");

                    b.Property<Guid?>("BanishedById")
                        .HasColumnType("uuid")
                        .HasColumnName("banished_by_id");

                    b.Property<string>("BanishmentReason")
                        .HasColumnType("text")
                        .HasColumnName("banishment_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_user_workspaces");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_workspaces_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_user_workspaces_deleted_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_user_workspaces_last_modified_by_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_user_workspaces_workspace_id");

                    b.HasIndex("UserId", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_workspaces_user_id_workspace_id");

                    b.ToTable("user_workspaces", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.Workspace.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_workspaces_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_workspaces_deleted_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_workspaces_last_modified_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_name");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("JChat.Domain.Entities.Channel.Channel", b =>
                {
                    b.HasOne("JChat.Domain.Entities.User.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_channels_users_created_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_channels_users_deleted_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasConstraintName("fk_channels_users_last_modified_by_id");

                    b.HasOne("JChat.Domain.Entities.Workspace.Workspace", "Workspace")
                        .WithMany("Channels")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channels_workspaces_workspace_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Channel.ChannelUser", b =>
                {
                    b.HasOne("JChat.Domain.Entities.Channel.Channel", null)
                        .WithMany("Users")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_users_channels_channel_id");

                    b.HasOne("JChat.Domain.Entities.User.User", null)
                        .WithMany("Channels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_users_users_user_id");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.Message", b =>
                {
                    b.HasOne("JChat.Domain.Entities.User.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_messages_users_created_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_messages_users_deleted_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasConstraintName("fk_messages_users_last_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessageHighlight", b =>
                {
                    b.HasOne("JChat.Domain.Entities.User.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_message_highlights_users_created_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_message_highlights_users_deleted_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasConstraintName("fk_message_highlights_users_last_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessageProjection", b =>
                {
                    b.HasOne("JChat.Domain.Entities.Message.MessageBodyType", "BodyType")
                        .WithMany()
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_projections_message_body_types_body_type_id");

                    b.HasOne("JChat.Domain.Entities.Message.MessagePriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_projections_message_priorities_priority_id");

                    b.Navigation("BodyType");

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessageReaction", b =>
                {
                    b.HasOne("JChat.Domain.Entities.User.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_message_reactions_users_created_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_message_reactions_users_deleted_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasConstraintName("fk_message_reactions_users_last_modified_by_id");

                    b.HasOne("JChat.Domain.Entities.Message.Message", null)
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_reactions_messages_message_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.MessageRecipient", b =>
                {
                    b.HasOne("JChat.Domain.Entities.User.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_message_recipients_users_created_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_message_recipients_users_deleted_by_id");

                    b.HasOne("JChat.Domain.Entities.Message.MessageRecipient", "ForwardedBy")
                        .WithMany()
                        .HasForeignKey("ForwardedById")
                        .HasConstraintName("fk_message_recipients_message_recipients_forwarded_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasConstraintName("fk_message_recipients_users_last_modified_by_id");

                    b.HasOne("JChat.Domain.Entities.Message.Message", null)
                        .WithMany("Recipients")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_recipients_messages_message_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ForwardedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Notifications.Notification", b =>
                {
                    b.HasOne("JChat.Domain.Entities.User.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_created_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.HasOne("JChat.Domain.Entities.Workspace.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .HasConstraintName("fk_notifications_workspaces_workspace_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("JChat.Domain.Entities.User.UserWorkspace", b =>
                {
                    b.HasOne("JChat.Domain.Entities.User.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_user_workspaces_users_created_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_user_workspaces_users_deleted_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasConstraintName("fk_user_workspaces_users_last_modified_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "User")
                        .WithMany("UserWorkspaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_workspaces_users_user_id");

                    b.HasOne("JChat.Domain.Entities.Workspace.Workspace", "Workspace")
                        .WithMany("UserWorkspaces")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_workspaces_workspaces_workspace_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Workspace.Workspace", b =>
                {
                    b.HasOne("JChat.Domain.Entities.User.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_workspaces_users_created_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_workspaces_users_deleted_by_id");

                    b.HasOne("JChat.Domain.Entities.User.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasConstraintName("fk_workspaces_users_last_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Channel.Channel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Message.Message", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("JChat.Domain.Entities.User.User", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("UserWorkspaces");
                });

            modelBuilder.Entity("JChat.Domain.Entities.Workspace.Workspace", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("UserWorkspaces");
                });
#pragma warning restore 612, 618
        }
    }
}
